### ISSUE TITLE
Getting 404 on IAD site

### ISSUE THREAD

**Issue by gregs5** [iadgov/Event-Forwarding-Guidance#8]
The report referenced in the README that sends one here:
https://www.iad.gov/iad/library/ia-guidance/security-configuration/applications/spotting-the-adversary-with-windows-event-log-monitoring.cfm

...results in a 404 if you click on the "GET FILE" icon.  Is there another location for this report? Not sure if this is version 2, but I was able to d/l a version of the file from this URL:

https://www.iad.gov/iad/library/reports/spotting-the-adversary-with-windows-event-log-monitoring.cfm

**Comment by iadgovuser1** [comment]
@gregs5 

Both are version 2. Sometimes reports are posted under multiple parent categories. The get file button refers to the same file location for both. The file downloads randomly fail in my experience. Not sure why. I've reported this to the responsible group in the past but I don't think they figured out the problem. It appears to happen more in Chrome than other browsers based on when I last looked at this issue..

**Comment by iadgovuser1** [comment]
New location is https://apps.nsa.gov/iaarchive/library/reports/spotting-the-adversary-with-windows-event-log-monitoring.cfm
